version: '3.8'

services:
  web:
    image: python:3.11-slim
    container_name: fastapi-app
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "${FASTAPI_PORT:-8000}:8000"  # FastAPI app port from .env file, default to 8000
    env_file:
      - .env.${ENVIRONMENT:-dev}      # Default to .env.dev if ENVIRONMENT is not specified
    depends_on:
      - db
      - redis
    networks:
      - backend_network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${FASTAPI_PORT:-8000}", "--reload"]

  db:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - .env.${ENVIRONMENT:-dev}    # Use the .env.dev file to define env variables for db service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"  # PostgreSQL port from .env file, default to 5432
    networks:
      - backend_network


  redis:
    image: redis:7.2
    container_name: redis-cache
    ports:
      - "${REDIS_PORT:-6379}:6379"  # Redis port from .env file, default to 6379
    networks:
      - backend_network
  
  pgadmin:
    image: dpage/pgadmin4:8.1   # pgAdmin4 Docker image
    container_name: pgadmin
    env_file:
      - .env.${ENVIRONMENT:-dev}    # Use the .env.dev file to define env variables for db service
    ports:
      - "${PGADMIN_PORT:-5050}:80"   # Expose pgAdmin on port 5050
    depends_on:
      - db
    networks:
      - backend_network

volumes:
  postgres_data:
  redis_data:

networks:
  bridge:
  backend_network:
    name: backend_network